name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.8.4'
        enable-stack: true
        stack-version: 'latest'
        
    - name: Cache stack
      uses: actions/cache@v2
      with:
        path: |
          ~/.stack
        key: ${{ runner.os }}-stackage

    - name: Build
      run: |
        stack build
        stack exec site build
      
    - name: Checkout build branch
      uses: actions/checkout@v1
      with:
        ref: 'build'
        clean: false

        
    - name: Copy to build branch
      run: cp -a _site/. .
      
    - name: Commit to build branch
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Auto Build
